In [1]:
import torch

In [15]:
torch.zeros((3, 4, 5))

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [4]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [5]:
torch.rand(2,3)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])

In [8]:
t =torch.randn((2, 5))
t.numel()

10

In [9]:
t.device

device(type='cpu')

In [11]:
x =t.to("mps")

In [12]:
x.device

device(type='mps', index=0)

In [16]:
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])


# Basic Indexing

In [17]:
tensor1[0]

tensor([1, 2, 3])

In [19]:
tensor1[1] [2]

tensor(6)

In [22]:
tensor1[1,2]
# preferred standard way to access elements

tensor(6)

In [23]:
tensor1[:,1:]

tensor([[2, 3],
        [5, 6]])

In [25]:
tensor1[1:, :2]

tensor([[4, 5]])

In [26]:
tensor1[-1]

tensor([4, 5, 6])

# masking

In [28]:
x = torch.tensor([1,2,3,4,5])
mask = x >2
x[mask]

tensor([3, 4, 5])

# Reshaping

In [31]:
x = torch.randn(1, 3, 1, 5)
print(x.shape)
# torch.Size([1, 3, 1, 5])

y = x.squeeze()
print(y)
y.shape
# torch.Size([3, 5])

torch.Size([1, 3, 1, 5])
tensor([[ 1.3549, -0.0112,  0.5928,  0.8067,  0.3174],
        [-0.3674,  0.6445, -1.6420,  0.3014, -0.9764],
        [-0.0254, -0.1521, -0.0268,  0.6461,  0.6105]])


torch.Size([3, 5])